language: ruby
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
addons:
  apt:
    packages:
      - libaugeas-dev
      - pkg-config
# use trusty travis infrastructure
sudo: required
dist: trusty
install: gem install -g
script:
    - COVERAGE=1 rake spec
    - rubocop
