language: ruby
rvm:
  - 2.2.7
  - 2.4.1
addons:
  apt:
    packages:
      - libaugeas-dev
      - pkg-config
# use trusty travis infrastructure
sudo: required
dist: trusty
install: gem install -g
script:
    - COVERAGE=1 rake spec
    - rubocop
